variables:
  project.name: 'PlatformName'
  project.upmSha: ''
  package.name: 'com.xrtk.platformname'
  package.version: ''
  EditorPath: ''
  LogDirectory: ''
  ${{ if eq( variables['build.reason'], 'PullRequest' ) }}:
    date: ''
  ${{ if ne( variables['build.reason'], 'PullRequest' ) }}:
    date: ${{ '$(Date:yyyyMMdd)' }}

name: $(package.name) ${{ coalesce( variables['date'], '$(System.PullRequest.PullRequestNumber)', '$(Date:yyyyMMdd)' ) }}$(Rev:.r)

pr:
  autoCancel: true
  branches:
   include:
     - master
     - development
     - feature/*
  paths:
    include:
    - azure-pipelines.yml
    - azure-pipelines/*
    - PlatformName/*
    exclude:
      - '*'
      - PlatformName/Packages/com.xrtk.platformname/README.md
      - PlatformName/Packages/com.xrtk.platformname/LICENSE.md
      - PlatformName/Packages/com.xrtk.platformname/.github/*

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - azure-pipelines.yml
      - azure-pipelines/*
      - PlatformName/*
    exclude:
      - '*'
      - PlatformName/Packages/com.xrtk.platformname/README.md
      - PlatformName/Packages/com.xrtk.platformname/LICENSE.md
      - PlatformName/Packages/com.xrtk.platformname/.github/*

extends:
  template: azure_pipelines/common.yml
  parameters:
    isReleaseBuild: ${{ and( eq(variables['Build.SourceBranchName'], 'master'), or( eq(variables['build.reason'], 'BatchedCI'), eq(variables['build.reason'], 'Manual') ) ) }}
